### PR TITLE
Clearer step headings in youtube.mdx

### PR DESCRIPTION
**Pull request by Kaszanas**
The steps are displayed without additional information in the sidebar:

image

I have added additional information to the headings.

### CODE REVIEW

**Comment by jamesread** [comment]
Much nicer, thanks!

**Comment by Kaszanas** [comment]
Will make it even nicer later 😉

But my guess is we need to verify if these are the correct secrets. 

I have images ready but I don't want to throw them into the repository just as binary files.

**Comment by jamesread** [comment]
@Kaszanas Throw the images in the repository as binary files, that's what images are :-)

**Comment by Kaszanas** [comment]
> @Kaszanas Throw the images in the repository as binary files, that's what images are :-) 

Yeah but in other instances you're using links to some GitHub hosting 🤔

**Pull request merged**
